### ISSUE TITLE
Overloadの条件について

### ISSUE THREAD

**Issue by raxtusi** [ROBOTIS-JAPAN-GIT/robotis-japan-support#12]
現在モータを使用しているなかで、モータが過負荷状態になる場合があります。
使用用途として、ものを掴むようなハンドに使用しているのですが、
把持する際対象物を傷づけに把持するために、
電流ベースの位置制御を使用しています。

使用していている電流として、
500 mAに制限して、使用しています。

また過負荷になる場合、
ものを掴んだ瞬間にOverload状態となります。

e-maulaを確認したところOverload条件として、
最大出力を超える永続的な負荷を検出します
しか書いておらず、Overloadの条件が明確に書かれていませんでした。

また、今回永続的な負荷ではなく、
瞬間的なエラーであると考えております。

このような場合のOverloadになる
条件や要因をご教授頂きたいです。

また個人的な考えではございますが、
以下の3点が考えられると思っています。

1点目は、電流値が500mAとの事で結果として最大トルクが絞られ
ている状態なので、更に低負荷でも過負荷となる可能性があると考えております。
したがって、今回最大出力はの電流値(500 mA)と考え、
過負荷になるのは、500 mAでは出力が少ないとの
認識であっているのか?

2点目は今回、ものを掴むようなハンドに使用しており、
把持する際対象物を傷づけに把持するために、
電流ベースの位置制御を使っております。
したがって、指令した位置にいつでも移動できるような使い方を使用しておりません。
このような場合、目標位置と現在位置との差分が大きい場合でも、
過負荷状態になるのでしょうか？
そのような場合、目標位置を下げることで解決できるのでしょうか？

3点目は先程も申し上げました通り、ものを掴むようなハンドに使用しているのですが、
把持速度が速いと衝突した力や慣性により、
過負荷になるのでしょうか？

大変申し訳ないのですが、
瞬間的に過負荷になる条件をご教授頂きたいです。

また個人的な認識も過負荷になる条件になるのか
ご教授頂きたいです。

**Comment by shiba-8ro** [comment]
ダイナミクセルは基本的に目標位置を継続的に推定するように設計されています。
目標位置に到達できない場合、ダイナミクセルは連続電流が流れ、オーバーロードが発生します。
過負荷の発生は、トルクと速度が高いほど速くなります。
残念ながら、オーバーロードは複雑な情報と設定に応じて発動する部分で、詳細条件が公開されていません。
ハンドの場合、物を持っていると連続的な電流が流れ、モーターに損傷を与える可能性があります。
これを防ぐために最大トルクを下げることをお勧めします。
最大トルクを50％未満に下げてもオーバーロードは発生しません。ただし、低トルクでも温度チェックなどで製品に無理に行くかチェックしてください。
お勧めできませんが、特別な状況では、設定によってオーバーロード機能をオフにすることもできます。

過負荷条件はDXLの破損を防ぐための機能です。 したがって、制限された電流値が十分に小さい場合、Overlaodはかかりません。 製品のモデル名が表記されていないため、500mAが適正線かどうかは確認が困難です。
