### ISSUE TITLE
ROS2 FoxyでSLAMを行うと突然異なる位置に飛んでMAPが生成される

### ISSUE THREAD

**Issue by kanpapa** [ROBOTIS-JAPAN-GIT/robotis-japan-support#21]
こちら何か情報はないでしょうか。ROS1だと全く問題はないのですが。
https://github.com/ROBOTIS-GIT/turtlebot3/issues/899

**Comment by shiba-8ro** [comment]
返信が遅くなり申し訳ございません。
https://github.com/ROBOTIS-GIT/turtlebot3/issues/899 の方のスレッドで対応を進めます。

**Comment by shiba-8ro** [comment]
本件、https://github.com/ROBOTIS-GIT/turtlebot3/issues/899 にて解決しクローズされました。
